'use client';
import { useEffect, useMemo, useState } from 'react';
type Player='Marcos'|'Belén'; type Entry={score:number;note?:string}; type Scores=Record<Player,(Entry|null)[]>;
const empty:Scores={Marcos:Array(7).fill(null),Belén:Array(7).fill(null)};
const total=(a:(Entry|null)[])=>a.reduce((s,x)=>s+(x?.score||0),0); const fmt=(n:number)=>n.toLocaleString('es-ES');
const valid=(x:any):x is Scores=>x&&Array.isArray(x.Marcos)&&Array.isArray(x.Belén)&&x.Marcos.length===7&&x.Belén.length===7;
export default function Home(){
 const[scores,setScores]=useState<Scores>(empty),[player,setPlayer]=useState<Player>('Marcos'),[day,setDay]=useState(1),[score,setScore]=useState(''),[note,setNote]=useState(''),[ready,setReady]=useState(false),[copied,setCopied]=useState(false);
 useEffect(()=>{try{const raw=location.hash.slice(1);if(raw){const d=JSON.parse(decodeURIComponent(atob(raw)));if(valid(d))setScores(d)}else{const rawLocal=localStorage.getItem('belen-scoreboard');if(rawLocal){const d=JSON.parse(rawLocal);if(valid(d))setScores(d)}}}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem('belen-scoreboard',JSON.stringify(scores))},[scores,ready]);
 const totals=useMemo(()=>({Marcos:total(scores.Marcos),Belén:total(scores.Belén)}),[scores]); const played=useMemo(()=>Math.max(...Object.values(scores).map(a=>a.filter(Boolean).length),0),[scores]);
 const loser=played===7&&totals.Marcos!==totals.Belén?(totals.Marcos<totals.Belén?'Marcos':'Belén'):null;
 function save(){const n=Number(score.replace(/\D/g,''));if(!n||n>25000||day<1||day>7)return;setScores(s=>({...s,[player]:s[player].map((x,i)=>i===day-1?{score:n,note:note.trim()||undefined}:x)}));setScore('');setNote('')}
 function share(){const encoded=btoa(encodeURIComponent(JSON.stringify(scores)));navigator.clipboard?.writeText(`${location.origin}${location.pathname}#${encoded}`);setCopied(true);setTimeout(()=>setCopied(false),1800)}
 function reset(){if(confirm('¿Borrar todas las puntuaciones?'))setScores(empty)} function copySummary(){const rows=Array.from({length:7},(_,i)=>`${i+1}. ${scores.Marcos[i]?.score??'—'} | ${scores.Belén[i]?.score??'—'}`).join('\n');navigator.clipboard?.writeText(`BELÉN VA A PERDER\n${rows}\nTOTAL Marcos: ${totals.Marcos}\nTOTAL Belén: ${totals.Belén}`)}
 if(!ready)return <main><div className="wrap"><p>Cargando…</p></div></main>;
 return <main><div className="wrap"><header><div><span className="eyebrow">GEOGUESSR · DAILY CHALLENGE</span><h1>BELÉN VA A PERDER</h1><p>7 días. Una sola perdedora.</p></div><div className="actions"><button onClick={share}>{copied?'Enlace copiado':'Compartir marcador'}</button><button onClick={copySummary}>Copiar tabla</button></div></header>
 <section className="hero"><div className="scorebox"><span>MARCOS</span><strong>{fmt(totals.Marcos)}</strong><small>{scores.Marcos.filter(Boolean).length}/7 días</small></div><div className="vs">VS</div><div className="scorebox"><span>BELÉN</span><strong>{fmt(totals.Belén)}</strong><small>{scores.Belén.filter(Boolean).length}/7 días</small></div></section>
 {loser?<div className="loser">EL RETO ES PARA <b>{loser.toUpperCase()}</b></div>:<div className="status">{played===0?'EMPEZAD CUANDO QUERÁIS':`DÍA ${played} · ${totals.Marcos===totals.Belén?'EMPATE':totals.Marcos>totals.Belén?'MARCOS VA POR DELANTE':'BELÉN VA POR DELANTE'}`}</div>}
 <section className="card"><h2>Apuntar partida</h2><div className="formgrid"><label>Jugador<select value={player} onChange={e=>setPlayer(e.target.value as Player)}><option value="Marcos">Marcos</option><option value="Belén">Belén</option></select></label><label>Día<select value={day} onChange={e=>setDay(Number(e.target.value))}>{[1,2,3,4,5,6,7].map(d=><option key={d} value={d}>Día {d}</option>)}</select></label><label>Puntuación<input inputMode="numeric" value={score} onChange={e=>setScore(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')save()}} placeholder="Ej. 21.437"/></label><label>Nota <span className="muted">(opcional)</span><input value={note} onChange={e=>setNote(e.target.value)}/></label></div><button className="primary" onClick={save}>Guardar puntuación</button><p className="hint">Después de añadir una puntuación, pulsa «Compartir marcador» y manda el enlace a la otra persona.</p></section>
 <section className="card"><div className="tablehead"><h2>Marcador</h2><button className="danger" onClick={reset}>Reiniciar</button></div><table><thead><tr><th>Día</th><th>Marcos</th><th>Belén</th><th>Ganador</th></tr></thead><tbody>{[1,2,3,4,5,6,7].map(d=>{const a=scores.Marcos[d-1]?.score,b=scores.Belén[d-1]?.score;return <tr key={d}><td>{d}</td><td>{a?fmt(a):'—'}</td><td>{b?fmt(b):'—'}</td><td>{a&&b?(a===b?'Empate':a>b?'Marcos':'Belén'):'—'}</td></tr>})}<tr className="total"><td>TOTAL</td><td>{fmt(totals.Marcos)}</td><td>{fmt(totals.Belén)}</td><td>{totals.Marcos===totals.Belén?'Empate':totals.Marcos>totals.Belén?'Marcos':'Belén'}</td></tr></tbody></table></section><footer>Regla: al terminar los 7 Daily Challenges, quien tenga MENOS puntos hace el reto.</footer></div>
 <style jsx global>{`*{box-sizing:border-box}body{margin:0;background:#0b0b0d;color:#f4f1ea;font-family:Inter,system-ui,sans-serif}button,input,select{font:inherit}button{cursor:pointer}.wrap{max-width:980px;margin:auto;padding:32px 20px 50px}header{display:flex;justify-content:space-between;gap:20px;align-items:flex-end;margin-bottom:28px}.eyebrow{font-size:12px;letter-spacing:.16em;color:#a9a29a}h1{font-size:clamp(34px,7vw,72px);line-height:.92;margin:8px 0;font-weight:950;letter-spacing:-.06em}header p{margin:0;color:#aaa39a}.actions{display:flex;gap:8px;flex-wrap:wrap}button{background:none;border:1px solid #39393e;color:#ddd;padding:10px 14px;border-radius:10px}.hero{display:grid;grid-template-columns:1fr auto 1fr;gap:14px;align-items:center;margin:25px 0}.scorebox{background:#151518;border:1px solid #29292f;border-radius:18px;padding:26px;text-align:center}.scorebox span{font-size:12px;letter-spacing:.16em;color:#aaa}.scorebox strong{display:block;font-size:clamp(36px,7vw,64px);letter-spacing:-.05em;margin:8px 0}.scorebox small{color:#777}.vs{font-weight:900;color:#777}.status,.loser{border-radius:14px;padding:14px;text-align:center;margin-bottom:18px;font-weight:800;letter-spacing:.08em}.status{background:#141416;color:#c9c2ba;border:1px solid #29292f}.loser{background:#f3e8d0;color:#0d0d0e}.card{background:#151518;border:1px solid #29292f;border-radius:18px;padding:22px;margin-top:16px}.card h2{margin:0 0 18px;font-size:20px}.formgrid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}label{font-size:12px;color:#aaa;display:grid;gap:7px}input,select{width:100%;background:#0e0e10;color:#f4f1ea;border:1px solid #38383e;border-radius:10px;padding:12px}.primary{margin-top:16px;width:100%;border:0;background:#f4f1ea;color:#0d0d0e;font-weight:900}.hint,footer{color:#666;font-size:12px}.tablehead{display:flex;justify-content:space-between;align-items:center}table{width:100%;border-collapse:collapse;font-size:14px}th,td{padding:12px 8px;border-bottom:1px solid #29292f;text-align:right}th:first-child,td:first-child{text-align:left}th{color:#777}.total td{border-bottom:0;padding-top:16px;font-weight:900}footer{text-align:center;margin-top:20px}@media(max-width:700px){header{align-items:flex-start;flex-direction:column}.hero{grid-template-columns:1fr 26px 1fr}.scorebox{padding:18px 10px}.formgrid{grid-template-columns:1fr}}`}</style></main> }